import "./globals.css";
import Header from './components/Header';
import NotificationProvider from "./components/notification/NotificationProvider";
import type {Metadata} from "next";
import {Funnel_Sans} from "next/font/google";
import {NextIntlClientProvider} from "next-intl";

const funnelSans = Funnel_Sans({
    variable: "--font-body",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html lang="en" className={funnelSans.variable}>
        <body>
        <NextIntlClientProvider>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
